### ISSUE TITLE
frontend 409 issue adressing missing

### ISSUE THREAD

**Issue by OnionKiller** [kob07kob/durer-quiz-frontend#12]
If error 409 then just hangs, no error message

**Comment by kob07kob** [comment]
When does it happen?

**Comment by OnionKiller** [comment]
Conflicting sequence, two people solving simultaneously.

**Comment by kob07kob** [comment]
now it always should show an error message (please refresh page) and loading button never structs
a test might be handy still :)

**Comment by radl97** [comment]
Is this fixed?

**Comment by kob07kob** [comment]
Yes
