### ISSUE TITLE
Add skip excercises option

### ISSUE THREAD

**Issue by OnionKiller** [kob07kob/durer-quiz-frontend#13]
FEATURE REQUEST
When time out, then add a button/option to skip to point summary.

**Comment by kob07kob** [comment]
<img width="1265" alt="Screenshot 2020-11-25 at 1 13 49" src="https://user-images.githubusercontent.com/26527010/100165838-8b8d7e00-2ebb-11eb-8f70-feb7968ba936.png">
Is this ok as design? It will only appear if time is over

**Comment by OnionKiller** [comment]
I would prefer if it's inline with the other design elements as a third button.
Can we change the colour? (I'll search for one)

**Comment by kob07kob** [comment]
![Screenshot 2020-11-26 at 13 00 23](https://user-images.githubusercontent.com/26527010/100348683-87f71580-2fe7-11eb-8dd3-3d4d3e98d9f2.png)

updated version

**Comment by OnionKiller** [comment]
Nice one, I like it.
