### ISSUE TITLE
End screen access issue

### ISSUE THREAD

**Issue by OnionKiller** [kob07kob/durer-quiz-frontend#14]
"Nem tudom hogy csináltam, de a végén, mikor először az eredmények után a szuperre nyomtam úgy dobott vissza a nyitólapra, hogy volt a folytat gomb volt amire kattintva random a 3/3 próbálkozásra dobott, bár ott, mikor megpróbáltam beküldeni valamit, akkor valami hibaüzenete volt és mikor újratöltöttem, akkor mér az eredmények jelent meg a kezdőlapon."

When ending, and then accessing end screen, the szuper(ok) gomb may leads to a page, where the option to submit solutions are still active. Possible counting issue.

**Comment by kob07kob** [comment]
same root problem as #11 should be fixed as well test still required

**Comment by radl97** [comment]
Is this fixed?

**Comment by kob07kob** [comment]
Yes this were fixed already
