### ISSUE TITLE
point calculation issues

### ISSUE THREAD

**Issue by OnionKiller** [kob07kob/durer-quiz-frontend#16]
Point calclulation has  significant issues,  shows fals results.
May be an indexing error.

**Comment by kob07kob** [comment]
Do you have an example?

**Comment by OnionKiller** [comment]
![image](https://user-images.githubusercontent.com/33357968/100124828-6c233080-2e7c-11eb-92b4-5ca23f1fd448.png)

**Comment by OnionKiller** [comment]
![image](https://user-images.githubusercontent.com/33357968/100125108-b0163580-2e7c-11eb-8ece-e49217e0a792.png)

**Comment by kob07kob** [comment]
done the sort function returned 1 and 0 instead of 1 and -1...
