### ISSUE TITLE
decimal number error message is english

### ISSUE THREAD

**Issue by OnionKiller** [kob07kob/durer-quiz-frontend#4]
![125542575_1754001634750733_2354866456948574876_o](https://user-images.githubusercontent.com/33357968/99303476-45984080-2851-11eb-812a-e1dc38fe2991.jpg)

**Comment by OnionKiller** [comment]
![125542575_1754001634750733_2354866456948574876_o](https://user-images.githubusercontent.com/33357968/99303476-45984080-2851-11eb-812a-e1dc38fe2991.jpg)

**Comment by kob07kob** [comment]
Done, (decimals were allowed in frontend, backend sent this message, now we only allow integers and the error message is hungarian)
